export const editableTiles = {
    0: "Dirt Block",
    1: "Stone Block",
    2: "Grass Block",
    6: "Iron Ore",
    7: "Copper Ore",
    8: "Gold Ore",
    9: "Silver Ore",
    22: "Demonite Ore",
    23: "Corrupt Grass Block",
    25: "Ebonstone Block",
    30: "Wood",
    32: "Corruption Thorns",
    37: "Meteorite",
    38: "Gray Brick",
    39: "Red Brick",
    40: "Clay Block",
    41: "Blue Brick",
    43: "Green Brick",
    44: "Pink Brick",
    45: "Gold Brick",
    46: "Silver Brick",
    47: "Copper Brick",
    48: "Spike",
    51: "Cobweb",
    52: "Vines",
    53: "Sand Block",
    54: "Glass",
    56: "Obsidian",
    57: "Ash Block",
    58: "Hellstone",
    59: "Mud Block",
    60: "Jungle Grass Block",
    62: "Jungle Vines",
    63: "Gem Sapphire",
    64: "Gem Ruby",
    65: "Gem Emerald",
    66: "Gem Topaz",
    67: "Gem Amethyst",
    68: "Gem Diamond",
    69: "Jungle Thorns",
    70: "Mushroom Grass Block",
    75: "Obsidian Brick",
    76: "Hellstone Brick",
    80: "Cactus",
    107: "Cobalt Ore",
    108: "Mythril Ore",
    109: "Hallowed Grass Block",
    111: "Adamantite Ore",
    112: "Ebonsand Block",
    115: "Hallowed Vines",
    116: "Pearlsand Block",
    117: "Pearlstone Block",
    118: "Pearlstone Brick",
    119: "Iridescent Brick",
    120: "Mudstone Block",
    121: "Cobalt Brick",
    122: "Mythril Brick",
    123: "Silt Block",
    124: "Wooden Beam",
    127: "Ice (Ice Rod)",
    130: "Active Stone Block",
    131: "Inactive Stone Block",
    140: "Demonite Brick",
    145: "Candy Cane Block",
    146: "Green Candy Cane Block",
    147: "Snow Block",
    148: "Snow Brick",
    150: "Adamantite Beam",
    151: "Sandstone Brick",
    152: "Ebonstone Brick",
    153: "Red Stucco",
    154: "Yellow Stucco",
    155: "Green Stucco",
    156: "Gray Stucco",
    157: "Ebonwood",
    158: "Rich Mahogany",
    159: "Pearlwood",
    160: "Rainbow Brick",
    161: "Ice Block",
    162: "Thin Ice",
    163: "Purple Ice Block",
    164: "Pink Ice Block",
    166: "Tin Ore",
    167: "Lead Ore",
    168: "Tungsten Ore",
    169: "Platinum Ore",
    170: "Pine Tree Block",
    175: "Tin Brick",
    176: "Tungsten Brick",
    177: "Platinum Brick",
    179: "Green Moss",
    180: "Yellow Moss",
    181: "Red Moss",
    182: "Blue Moss",
    183: "Purple Moss",
    188: "Cactus",
    189: "Cloud",
    190: "Glowing Mushroom",
    191: "Living Wood Wand",
    192: "Leaf Wand",
    193: "Slime Block",
    194: "Bone Block",
    195: "Flesh Block",
    196: "Rain Cloud",
    197: "Frozen Slime Block",
    198: "Asphalt Block",
    199: "Crimson Grass Block",
    200: "Red Ice Block",
    202: "Sunplate Block",
    203: "Crimstone Block",
    204: "Crimtane Ore",
    205: "Crimson Vine",
    206: "Ice Brick",
    208: "Shadewood",
    211: "Chlorophyte Ore",
    213: "Rope",
    214: "Chain",
    221: "Palladium Ore",
    222: "Orichalcum Ore",
    223: "Titanium Ore",
    224: "Slush Block",
    225: "Hive Wand",
    226: "Lihzahrd Brick",
    229: "Honey Block",
    230: "Crispy Honey Block",
    232: "Wooden Spike",
    234: "Crimsand Block",
    248: "Palladium Column",
    249: "Bubblegum Block",
    250: "Titanstone Block",
    251: "Pumpkin",
    252: "Hay",
    253: "Spooky Wood",
    255: "Amethyst Gemspark Block (Offline)",
    256: "Topaz Gemspark Block (Offline)",
    257: "Sapphire Gemspark Block (Offline)",
    258: "Emerald Gemspark Block (Offline)",
    259: "Ruby Gemspark Block (Offline)",
    260: "Diamond Gemspark Block (Offline)",
    261: "Amber Gemspark Block (Offline)",
    262: "Amethyst Gemspark Block",
    263: "Topaz Gemspark Block",
    264: "Sapphire Gemspark Block",
    265: "Emerald Gemspark Block",
    266: "Ruby Gemspark Block",
    267: "Diamond Gemspark Block",
    268: "Amber Gemspark Block",
    272: "Cog",
    273: "Stone Slab",
    274: "Sandstone Slab",
    284: "Copper Plating",
    311: "Dynasty Wood",
    312: "Red Dynasty Shingles",
    313: "Blue Dynasty Shingles",
    315: "Coralstone Block",
    321: "Boreal Wood",
    322: "Palm Wood",
    325: "Tin Plating",
    326: "Waterfall Block",
    327: "Lavafall Block",
    328: "Confetti Block",
    329: "Midnight Confetti Block",
    330: "Copper Coin Pile",
    331: "Silver Coin Pile",
    332: "Gold Coin Pile",
    333: "Platinum Coin Pile",
    336: "Living Fire Block",
    340: "Living Cursed Fire",
    341: "Living Demon Fire",
    342: "Living Frost Fire",
    343: "Living Ichor",
    344: "Living Ultrabright Fire",
    345: "Honeyfall Block",
    346: "Chlorophyte Brick",
    347: "Crimtane Brick",
    348: "Shroomite Plating",
    350: "Martian Conduit Plating",
    351: "Chimney Smoke",
    352: "Crimtane Thorns",
    353: "Vine Rope",
    357: "Smooth Marble Block",
    365: "Silk Rope",
    366: "Web Rope",
    367: "Marble Block",
    368: "Granite Block",
    369: "Smooth Granite Block",
    370: "Meteorite Brick",
    371: "Pink Slime Block",
    379: "Bubble",
    381: "Lava Moss",
    382: "Vine Flowers",
    383: "Living Mahogany",
    384: "Living Mahogany Leaves",
    385: "Crystal Block",
    396: "Sandstone",
    397: "Hardened Sand",
    398: "Corrupt Hardened Sand",
    399: "Crimson Hardened Sand",
    400: "Corrupt Sandstone",
    401: "Crimson Sandstone",
    402: "Hallow Hardened Sand",
    403: "Hallow Sandstone",
    404: "Desert Fossil",
    407: "Fossil Ore",
    408: "Lunar Ore",
    409: "Lunar Brick",
    415: "Lunar Block Solar",
    416: "Lunar Block Vortex",
    417: "Lunar Block Nebula",
    418: "Lunar Block Stardust",
    421: "Conveyor Belt (CW)",
    422: "Conveyor Belt (CCW)",
    426: "Red Team Block",
    430: "Green Team Block",
    431: "Blue Team Block",
    432: "Yellow Team Block",
    433: "Pink Team Block",
    434: "White Team Block",
    446: "Silly Pink Balloon",
    447: "Silly Purple Balloon",
    448: "Silly Green Balloon",
    449: "Blue Streamer",
    450: "Green Streamer",
    451: "Pink Streamer",
    458: "Sandfall",
    459: "Snowfall",
    460: "Snow Cloud",
};

export const editableWalls = {
    1: "Stone Wall",
    2: "Dirt Wall",
    3: "Ebonstone Wall",
    4: "Wood Wall",
    5: "Gray Brick Wall",
    6: "Red Brick Wall",
    7: "Dungeon Blue Brick Wall",
    8: "Dungeon Green Brick Wall",
    9: "Dungeon Pink Brick Wall",
    10: "Gold Brick Wall",
    11: "Silver Brick Wall",
    12: "Copper Brick Wall",
    13: "Hellstone Wall",
    14: "Obsidian Wall",
    15: "Mud Wall",
    16: "Player Dirt Wall",
    17: "Player Blue Brick Wall",
    18: "Player Green Brick Wall",
    19: "Player Pink Brick Wall",
    20: "Player Obsidian Wall",
    21: "Glass Wall",
    22: "Pearlstone Brick",
    23: "Iridescent Wall",
    24: "Mudstone Wall",
    25: "Cobalt Brick Wall",
    26: "Mythril Brick Wall",
    27: "Planked Wall",
    28: "Pearlstone Wall",
    29: "Red Candy Cane Wall",
    30: "Green Candy Cane Wall",
    31: "Snow Brick Wall",
    32: "Adamantite Beam Wall",
    33: "Demonite Brick Wall",
    34: "Sandstone Brick Wall",
    35: "Ebonstone Brick Wall",
    36: "Red Stucco Wall",
    37: "Yellow Stucco Wall",
    38: "Green Stucco Wall",
    39: "Gray Stucco Wall",
    40: "Snow Wall",
    41: "Ebonwood Wall",
    42: "Rich Mahogany Wall",
    43: "Pearlwood Wall",
    44: "Rainbow Brick Wall",
    45: "Tin Brick Wall",
    46: "Tungsten Brick Wall",
    47: "Platinum Brick Wall",
    48: "Amethyst Gemstone Wall",
    49: "Topaz Gemstone Wall",
    50: "Sapphire Gemstone Wall",
    51: "Emerald Gemstone Wall",
    52: "Ruby Gemstone Wall",
    53: "Diamond Gemstone Wall",
    54: "Green Moss Cave Wall",
    55: "Yellow Moss Cave Wall",
    56: "Red Moss Cave Wall",
    57: "Blue Moss Cave Wall",
    58: "Purple Moss Cave Wall",
    59: "Cave Wall",
    60: "Moss Wall",
    61: "Iron Cave Wall",
    62: "Spider Wall",
    63: "Grass Wall",
    64: "Jungle Wall",
    65: "Flower Wall",
    66: "Player Grass Wall",
    67: "Player Jungle Wall",
    68: "Player Flower Wall",
    69: "Corruption Jungle Wall",
    70: "Hallowed Jungle Wall",
    71: "Ice Wall",
    72: "Cactus Wall",
    73: "Cloud Wall",
    74: "Mushroom Wall",
    75: "Bone Block Wall",
    76: "Slime Block Wall",
    77: "Flesh Block Wall",
    78: "Livingwood Wall",
    79: "Obsidian Cave Wall",
    80: "Mushroom Cave Wall",
    81: "Crimson Jungle Wall",
    82: "Disc Wall",
    83: "Crimstone Wall",
    84: "Ice Brick Wall",
    85: "Shadewood Wall",
    86: "Hive Wall",
    87: "Lihzahrd Brick Wall",
    88: "Purple Stained Glass",
    89: "Yellow Stained Glass",
    90: "Blue Stained Glass",
    91: "Green Stained Glass",
    92: "Red Stained Glass",
    93: "Multicolored Stained Glass",
    94: "Dungeon Blue Slab Wall",
    95: "Dungeon Blue Tiled Wall",
    96: "Dungeon Pink Slab Wall",
    97: "Dungeon Pink Tiled Wall",
    98: "Dungeon Green Slab Wall",
    99: "Dungeon Green Tiled Wall",
    100: "Player Blue Slab Wall",
    101: "Player Blue Tiled Wall",
    102: "Player Pink Slab Wall",
    103: "Player Pink Tiled Wall",
    104: "Player Green Slab Wall",
    105: "Player Green Tiled Wall",
    106: "Wooden Fence",
    107: "Lead Fence",
    108: "Hive Wall",
    109: "Palladium Column Wall",
    110: "Bubblegum Block Wall",
    111: "Titanstone Block Wall",
    112: "Player Lihzahrd Brick Wall",
    113: "Pumpkin Wall",
    114: "Hay Wall",
    115: "Spooky Wood Wall",
    116: "Christmas Tree Wallpaper",
    117: "Ornament Wallpaper",
    118: "Candy Cane Wallpaper",
    119: "Festive Wallpaper",
    120: "Stars Wallpaper",
    121: "Squiggles Wallpaper",
    122: "Snowflake Wallpaper",
    123: "Krampus Horn Wallpaper",
    124: "Bluegreen Wallpaper",
    125: "Grinch Finger Wallpaper",
    126: "Fancy Grey Wallpaper",
    127: "Ice Floe Wallpaper",
    128: "Music Wallpaper",
    129: "Purple Rain Wallpaper",
    130: "Rainbow Wallpaper",
    131: "Sparkle Stone Wallpaper",
    132: "Starlit Heaven Wallpaper",
    133: "Bubble Wallpaper",
    134: "Copper Pipe Wallpaper",
    135: "Ducky Wallpaper",
    136: "Waterfall Wall",
    137: "Lavafall Wall",
    138: "Ebonwood Fence",
    139: "Rich Mahogany Fence",
    140: "Pearlwood Fence",
    141: "Shadewood Fence",
    142: "White Dynasty Wall",
    143: "Blue Dynasty Wall",
    144: "Mystic Rune Wallpaper",
    145: "Iron Fence",
    146: "Copper Plating",
    147: "Stone Slab Wall",
    148: "Sail",
    149: "Boreal Wood Wall",
    150: "Boreal Wood Fence",
    151: "Palm Wood Wall",
    152: "Palm Wood Fence",
    153: "Amber Gemspark Wall",
    154: "Amethyst Gemspark Wall",
    155: "Diamond Gemspark Wall",
    156: "Emerald Gemspark Wall",
    157: "Offline Amber Gemspark Wall",
    158: "Offline Amethyst Gemspark Wall",
    159: "Offline Diamond Gemspark Wall",
    160: "Offline Emerald Gemspark Wall",
    161: "Offline Ruby Gemspark Wall",
    162: "Offline Sapphire Gemspark Wall",
    163: "Offline Topaz Gemspark Wall",
    164: "Ruby Gemspark Wall",
    165: "Sapphire Gemspark Wall",
    166: "Topaz Gemspark Wall",
    167: "Tin Plating Wall",
    168: "Confetti Wall",
    169: "Midnight Confetti Wall",
    170: "Unique Cave Wall 7 (natural)",
    171: "Unique Cave Wall 8 (natural)",
    172: "Honeyfall Wall",
    173: "Chlorophyte Brick Wall",
    174: "Crimtane Brick Wall",
    175: "Shroomite Plating Wall",
    176: "Martian Conduit Wall",
    177: "Hellstone Brick Wall",
    178: "Marble (natural)",
    179: "Smooth Marble Wall",
    180: "Granite (natural)",
    181: "Smooth Granite Wall",
    182: "Meteorite Brick Wall",
    183: "Marble Wall",
    184: "Granite Wall",
    185: "Cave 8 (natural)",
    186: "Crystal Block Wall",
    187: "Sandstone Wall",
    188: "Corruption 1 (natural)",
    189: "Corruption 2 (natural)",
    190: "Corruption 3 (natural)",
    191: "Corruption 4 (natural)",
    192: "Crimson 1 (natural)",
    193: "Crimson 2 (natural)",
    194: "Crimson 3 (natural)",
    195: "Crimson 4 (natural)",
    196: "Dirt 1 (natural)",
    197: "Dirt 2 (natural)",
    198: "Dirt 3 (natural)",
    199: "Dirt 4 (natural)",
    200: "Hallow 1 (natural)",
    201: "Hallow 2 (natural)",
    202: "Hallow 3 (natural)",
    203: "Hallow 4 (natural)",
    204: "Jungle 1 (natural)",
    205: "Jungle 2 (natural)",
    206: "Jungle 3 (natural)",
    207: "Jungle 4 (natural)",
    208: "Lava 1 (natural)",
    209: "Lava 2 (natural)",
    210: "Lava 3 (natural)",
    211: "Lava 4 (natural)",
    212: "Rocks 1 (natural)",
    213: "Rocks 2 (natural)",
    214: "Rocks 3 (natural)",
    215: "Rocks 4 (natural)",
    216: "Hardened Sand Wall",
    217: "Hardened Ebonsand Wall",
    218: "Hardened Crimsand Wall",
    219: "Hardened Pearlsand Wall",
    220: "Ebonsandstone Wall",
    221: "Crimsandstone Wall",
    222: "Pearlsandstone Wall",
    223: "Desert Fossil Wall",
    224: "Lunar Brick Wall",
    225: "Cog Wall",
    226: "Sandfall Wall",
    227: "Snowfall Wall",
    228: "Silly Pink Balloon Wall",
    229: "Silly Purple Balloon Wall",
    230: "Silly Green Balloon Wall",
};