export default {
    1: "Stone Wall",
    2: "Dirt Wall",
    3: "Ebonstone Wall",
    4: "Wood Wall",
    5: "Gray Brick Wall",
    6: "Red Brick Wall",
    7: "Dungeon Blue Brick Wall",
    8: "Dungeon Green Brick Wall",
    9: "Dungeon Pink Brick Wall",
    10: "Gold Brick Wall",
    11: "Silver Brick Wall",
    12: "Copper Brick Wall",
    13: "Hellstone Wall",
    14: "Obsidian Wall",
    15: "Mud Wall",
    16: "Player Dirt Wall",
    17: "Player Blue Brick Wall",
    18: "Player Green Brick Wall",
    19: "Player Pink Brick Wall",
    20: "Player Obsidian Wall",
    21: "Glass Wall",
    22: "Pearlstone Brick",
    23: "Iridescent Wall",
    24: "Mudstone Wall",
    25: "Cobalt Brick Wall",
    26: "Mythril Brick Wall",
    27: "Planked Wall",
    28: "Pearlstone Wall",
    29: "Red Candy Cane Wall",
    30: "Green Candy Cane Wall",
    31: "Snow Brick Wall",
    32: "Adamantite Beam Wall",
    33: "Demonite Brick Wall",
    34: "Sandstone Brick Wall",
    35: "Ebonstone Brick Wall",
    36: "Red Stucco Wall",
    37: "Yellow Stucco Wall",
    38: "Green Stucco Wall",
    39: "Gray Stucco Wall",
    40: "Snow Wall",
    41: "Ebonwood Wall",
    42: "Rich Mahogany Wall",
    43: "Pearlwood Wall",
    44: "Rainbow Brick Wall",
    45: "Tin Brick Wall",
    46: "Tungsten Brick Wall",
    47: "Platinum Brick Wall",
    48: "Amethyst Gemstone Wall",
    49: "Topaz Gemstone Wall",
    50: "Sapphire Gemstone Wall",
    51: "Emerald Gemstone Wall",
    52: "Ruby Gemstone Wall",
    53: "Diamond Gemstone Wall",
    54: "Green Moss Cave Wall",
    55: "Yellow Moss Cave Wall",
    56: "Red Moss Cave Wall",
    57: "Blue Moss Cave Wall",
    58: "Purple Moss Cave Wall",
    59: "Cave Wall",
    60: "Moss Wall",
    61: "Iron Cave Wall",
    62: "Spider Wall",
    63: "Grass Wall",
    64: "Jungle Wall",
    65: "Flower Wall",
    66: "Player Grass Wall",
    67: "Player Jungle Wall",
    68: "Player Flower Wall",
    69: "Corruption Jungle Wall",
    70: "Hallowed Jungle Wall",
    71: "Ice Wall",
    72: "Cactus Wall",
    73: "Cloud Wall",
    74: "Mushroom Wall",
    75: "Bone Block Wall",
    76: "Slime Block Wall",
    77: "Flesh Block Wall",
    78: "Livingwood Wall",
    79: "Obsidian Cave Wall",
    80: "Mushroom Cave Wall",
    81: "Crimson Jungle Wall",
    82: "Disc Wall",
    83: "Crimstone Wall",
    84: "Ice Brick Wall",
    85: "Shadewood Wall",
    86: "Hive Wall",
    87: "Lihzahrd Brick Wall",
    88: "Purple Stained Glass",
    89: "Yellow Stained Glass",
    90: "Blue Stained Glass",
    91: "Green Stained Glass",
    92: "Red Stained Glass",
    93: "Multicolored Stained Glass",
    94: "Dungeon Blue Slab Wall",
    95: "Dungeon Blue Tiled Wall",
    96: "Dungeon Pink Slab Wall",
    97: "Dungeon Pink Tiled Wall",
    98: "Dungeon Green Slab Wall",
    99: "Dungeon Green Tiled Wall",
    100: "Player Blue Slab Wall",
    101: "Player Blue Tiled Wall",
    102: "Player Pink Slab Wall",
    103: "Player Pink Tiled Wall",
    104: "Player Green Slab Wall",
    105: "Player Green Tiled Wall",
    106: "Wooden Fence",
    107: "Lead Fence",
    108: "Hive Wall",
    109: "Palladium Column Wall",
    110: "Bubblegum Block Wall",
    111: "Titanstone Block Wall",
    112: "Player Lihzahrd Brick Wall",
    113: "Pumpkin Wall",
    114: "Hay Wall",
    115: "Spooky Wood Wall",
    116: "Christmas Tree Wallpaper",
    117: "Ornament Wallpaper",
    118: "Candy Cane Wallpaper",
    119: "Festive Wallpaper",
    120: "Stars Wallpaper",
    121: "Squiggles Wallpaper",
    122: "Snowflake Wallpaper",
    123: "Krampus Horn Wallpaper",
    124: "Bluegreen Wallpaper",
    125: "Grinch Finger Wallpaper",
    126: "Fancy Grey Wallpaper",
    127: "Ice Floe Wallpaper",
    128: "Music Wallpaper",
    129: "Purple Rain Wallpaper",
    130: "Rainbow Wallpaper",
    131: "Sparkle Stone Wallpaper",
    132: "Starlit Heaven Wallpaper",
    133: "Bubble Wallpaper",
    134: "Copper Pipe Wallpaper",
    135: "Ducky Wallpaper",
    136: "Waterfall Wall",
    137: "Lavafall Wall",
    138: "Ebonwood Fence",
    139: "Rich Mahogany Fence",
    140: "Pearlwood Fence",
    141: "Shadewood Fence",
    142: "White Dynasty Wall",
    143: "Blue Dynasty Wall",
    144: "Mystic Rune Wallpaper",
    145: "Iron Fence",
    146: "Copper Plating",
    147: "Stone Slab Wall",
    148: "Sail",
    149: "Boreal Wood Wall",
    150: "Boreal Wood Fence",
    151: "Palm Wood Wall",
    152: "Palm Wood Fence",
    153: "Amber Gemspark Wall",
    154: "Amethyst Gemspark Wall",
    155: "Diamond Gemspark Wall",
    156: "Emerald Gemspark Wall",
    157: "Offline Amber Gemspark Wall",
    158: "Offline Amethyst Gemspark Wall",
    159: "Offline Diamond Gemspark Wall",
    160: "Offline Emerald Gemspark Wall",
    161: "Offline Ruby Gemspark Wall",
    162: "Offline Sapphire Gemspark Wall",
    163: "Offline Topaz Gemspark Wall",
    164: "Ruby Gemspark Wall",
    165: "Sapphire Gemspark Wall",
    166: "Topaz Gemspark Wall",
    167: "Tin Plating Wall",
    168: "Confetti Wall",
    169: "Midnight Confetti Wall",
    170: "Unique Cave Wall 7 (natural)",
    171: "Unique Cave Wall 8 (natural)",
    172: "Honeyfall Wall",
    173: "Chlorophyte Brick Wall",
    174: "Crimtane Brick Wall",
    175: "Shroomite Plating Wall",
    176: "Martian Conduit Wall",
    177: "Hellstone Brick Wall",
    178: "Marble (natural)",
    179: "Smooth Marble Wall",
    180: "Granite (natural)",
    181: "Smooth Granite Wall",
    182: "Meteorite Brick Wall",
    183: "Marble Wall",
    184: "Granite Wall",
    185: "Cave 8 (natural)",
    186: "Crystal Block Wall",
    187: "Sandstone Wall",
    188: "Corruption 1 (natural)",
    189: "Corruption 2 (natural)",
    190: "Corruption 3 (natural)",
    191: "Corruption 4 (natural)",
    192: "Crimson 1 (natural)",
    193: "Crimson 2 (natural)",
    194: "Crimson 3 (natural)",
    195: "Crimson 4 (natural)",
    196: "Dirt 1 (natural)",
    197: "Dirt 2 (natural)",
    198: "Dirt 3 (natural)",
    199: "Dirt 4 (natural)",
    200: "Hallow 1 (natural)",
    201: "Hallow 2 (natural)",
    202: "Hallow 3 (natural)",
    203: "Hallow 4 (natural)",
    204: "Jungle 1 (natural)",
    205: "Jungle 2 (natural)",
    206: "Jungle 3 (natural)",
    207: "Jungle 4 (natural)",
    208: "Lava 1 (natural)",
    209: "Lava 2 (natural)",
    210: "Lava 3 (natural)",
    211: "Lava 4 (natural)",
    212: "Rocks 1 (natural)",
    213: "Rocks 2 (natural)",
    214: "Rocks 3 (natural)",
    215: "Rocks 4 (natural)",
    216: "Hardened Sand Wall",
    217: "Hardened Ebonsand Wall",
    218: "Hardened Crimsand Wall",
    219: "Hardened Pearlsand Wall",
    220: "Ebonsandstone Wall",
    221: "Crimsandstone Wall",
    222: "Pearlsandstone Wall",
    223: "Desert Fossil Wall",
    224: "Lunar Brick Wall",
    225: "Cog Wall",
    226: "Sandfall Wall",
    227: "Snowfall Wall",
    228: "Silly Pink Balloon Wall",
    229: "Silly Purple Balloon Wall",
    230: "Silly Green Balloon Wall",
};